package com.niejinkun.springcloud.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.rate_type
     *
     * @mbg.generated
     */
    private Byte rateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.rate
     *
     * @mbg.generated
     */
    private Long rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.rate_max
     *
     * @mbg.generated
     */
    private Long rateMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.rate_min
     *
     * @mbg.generated
     */
    private Long rateMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.float_rate
     *
     * @mbg.generated
     */
    private Long floatRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.investment_term
     *
     * @mbg.generated
     */
    private BigDecimal investmentTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.investment_min_money
     *
     * @mbg.generated
     */
    private BigDecimal investmentMinMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.investment_max_money
     *
     * @mbg.generated
     */
    private BigDecimal investmentMaxMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.total_money
     *
     * @mbg.generated
     */
    private BigDecimal totalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.left_money
     *
     * @mbg.generated
     */
    private BigDecimal leftMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.people
     *
     * @mbg.generated
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.foot_name
     *
     * @mbg.generated
     */
    private String footName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.channel
     *
     * @mbg.generated
     */
    private Short channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.open_time
     *
     * @mbg.generated
     */
    private Integer openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.vip_open_time
     *
     * @mbg.generated
     */
    private Integer vipOpenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.rate_time
     *
     * @mbg.generated
     */
    private Integer rateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.open_status
     *
     * @mbg.generated
     */
    private Byte openStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_basic.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public ProductBasic(Integer id, String code, Byte type, Byte status, Byte rateType, Long rate, Long rateMax, Long rateMin, Long floatRate, BigDecimal investmentTerm, BigDecimal investmentMinMoney, BigDecimal investmentMaxMoney, BigDecimal totalMoney, BigDecimal leftMoney, Integer people, String img, String title, String footName, Short channel, Integer openTime, Integer vipOpenTime, Integer rateTime, Byte openStatus, Date updateAt, Date createAt) {
        this.id = id;
        this.code = code;
        this.type = type;
        this.status = status;
        this.rateType = rateType;
        this.rate = rate;
        this.rateMax = rateMax;
        this.rateMin = rateMin;
        this.floatRate = floatRate;
        this.investmentTerm = investmentTerm;
        this.investmentMinMoney = investmentMinMoney;
        this.investmentMaxMoney = investmentMaxMoney;
        this.totalMoney = totalMoney;
        this.leftMoney = leftMoney;
        this.people = people;
        this.img = img;
        this.title = title;
        this.footName = footName;
        this.channel = channel;
        this.openTime = openTime;
        this.vipOpenTime = vipOpenTime;
        this.rateTime = rateTime;
        this.openStatus = openStatus;
        this.updateAt = updateAt;
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.id
     *
     * @return the value of product_basic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.code
     *
     * @return the value of product_basic.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.type
     *
     * @return the value of product_basic.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.status
     *
     * @return the value of product_basic.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.rate_type
     *
     * @return the value of product_basic.rate_type
     *
     * @mbg.generated
     */
    public Byte getRateType() {
        return rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.rate
     *
     * @return the value of product_basic.rate
     *
     * @mbg.generated
     */
    public Long getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.rate_max
     *
     * @return the value of product_basic.rate_max
     *
     * @mbg.generated
     */
    public Long getRateMax() {
        return rateMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.rate_min
     *
     * @return the value of product_basic.rate_min
     *
     * @mbg.generated
     */
    public Long getRateMin() {
        return rateMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.float_rate
     *
     * @return the value of product_basic.float_rate
     *
     * @mbg.generated
     */
    public Long getFloatRate() {
        return floatRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.investment_term
     *
     * @return the value of product_basic.investment_term
     *
     * @mbg.generated
     */
    public BigDecimal getInvestmentTerm() {
        return investmentTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.investment_min_money
     *
     * @return the value of product_basic.investment_min_money
     *
     * @mbg.generated
     */
    public BigDecimal getInvestmentMinMoney() {
        return investmentMinMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.investment_max_money
     *
     * @return the value of product_basic.investment_max_money
     *
     * @mbg.generated
     */
    public BigDecimal getInvestmentMaxMoney() {
        return investmentMaxMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.total_money
     *
     * @return the value of product_basic.total_money
     *
     * @mbg.generated
     */
    public BigDecimal getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.left_money
     *
     * @return the value of product_basic.left_money
     *
     * @mbg.generated
     */
    public BigDecimal getLeftMoney() {
        return leftMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.people
     *
     * @return the value of product_basic.people
     *
     * @mbg.generated
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.img
     *
     * @return the value of product_basic.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.title
     *
     * @return the value of product_basic.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.foot_name
     *
     * @return the value of product_basic.foot_name
     *
     * @mbg.generated
     */
    public String getFootName() {
        return footName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.channel
     *
     * @return the value of product_basic.channel
     *
     * @mbg.generated
     */
    public Short getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.open_time
     *
     * @return the value of product_basic.open_time
     *
     * @mbg.generated
     */
    public Integer getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.vip_open_time
     *
     * @return the value of product_basic.vip_open_time
     *
     * @mbg.generated
     */
    public Integer getVipOpenTime() {
        return vipOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.rate_time
     *
     * @return the value of product_basic.rate_time
     *
     * @mbg.generated
     */
    public Integer getRateTime() {
        return rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.open_status
     *
     * @return the value of product_basic.open_status
     *
     * @mbg.generated
     */
    public Byte getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.update_at
     *
     * @return the value of product_basic.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_basic.create_at
     *
     * @return the value of product_basic.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }
}