package com.niejinkun.springcloud.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductBasicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public ProductBasicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNull() {
            addCriterion("rate_type is null");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNotNull() {
            addCriterion("rate_type is not null");
            return (Criteria) this;
        }

        public Criteria andRateTypeEqualTo(Byte value) {
            addCriterion("rate_type =", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotEqualTo(Byte value) {
            addCriterion("rate_type <>", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThan(Byte value) {
            addCriterion("rate_type >", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("rate_type >=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThan(Byte value) {
            addCriterion("rate_type <", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThanOrEqualTo(Byte value) {
            addCriterion("rate_type <=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeIn(List<Byte> values) {
            addCriterion("rate_type in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotIn(List<Byte> values) {
            addCriterion("rate_type not in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeBetween(Byte value1, Byte value2) {
            addCriterion("rate_type between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("rate_type not between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(Long value) {
            addCriterion("rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(Long value) {
            addCriterion("rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(Long value) {
            addCriterion("rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(Long value) {
            addCriterion("rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(Long value) {
            addCriterion("rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(Long value) {
            addCriterion("rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<Long> values) {
            addCriterion("rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<Long> values) {
            addCriterion("rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(Long value1, Long value2) {
            addCriterion("rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(Long value1, Long value2) {
            addCriterion("rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateMaxIsNull() {
            addCriterion("rate_max is null");
            return (Criteria) this;
        }

        public Criteria andRateMaxIsNotNull() {
            addCriterion("rate_max is not null");
            return (Criteria) this;
        }

        public Criteria andRateMaxEqualTo(Long value) {
            addCriterion("rate_max =", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxNotEqualTo(Long value) {
            addCriterion("rate_max <>", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxGreaterThan(Long value) {
            addCriterion("rate_max >", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxGreaterThanOrEqualTo(Long value) {
            addCriterion("rate_max >=", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxLessThan(Long value) {
            addCriterion("rate_max <", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxLessThanOrEqualTo(Long value) {
            addCriterion("rate_max <=", value, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxIn(List<Long> values) {
            addCriterion("rate_max in", values, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxNotIn(List<Long> values) {
            addCriterion("rate_max not in", values, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxBetween(Long value1, Long value2) {
            addCriterion("rate_max between", value1, value2, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMaxNotBetween(Long value1, Long value2) {
            addCriterion("rate_max not between", value1, value2, "rateMax");
            return (Criteria) this;
        }

        public Criteria andRateMinIsNull() {
            addCriterion("rate_min is null");
            return (Criteria) this;
        }

        public Criteria andRateMinIsNotNull() {
            addCriterion("rate_min is not null");
            return (Criteria) this;
        }

        public Criteria andRateMinEqualTo(Long value) {
            addCriterion("rate_min =", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinNotEqualTo(Long value) {
            addCriterion("rate_min <>", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinGreaterThan(Long value) {
            addCriterion("rate_min >", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinGreaterThanOrEqualTo(Long value) {
            addCriterion("rate_min >=", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinLessThan(Long value) {
            addCriterion("rate_min <", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinLessThanOrEqualTo(Long value) {
            addCriterion("rate_min <=", value, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinIn(List<Long> values) {
            addCriterion("rate_min in", values, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinNotIn(List<Long> values) {
            addCriterion("rate_min not in", values, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinBetween(Long value1, Long value2) {
            addCriterion("rate_min between", value1, value2, "rateMin");
            return (Criteria) this;
        }

        public Criteria andRateMinNotBetween(Long value1, Long value2) {
            addCriterion("rate_min not between", value1, value2, "rateMin");
            return (Criteria) this;
        }

        public Criteria andFloatRateIsNull() {
            addCriterion("float_rate is null");
            return (Criteria) this;
        }

        public Criteria andFloatRateIsNotNull() {
            addCriterion("float_rate is not null");
            return (Criteria) this;
        }

        public Criteria andFloatRateEqualTo(Long value) {
            addCriterion("float_rate =", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateNotEqualTo(Long value) {
            addCriterion("float_rate <>", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateGreaterThan(Long value) {
            addCriterion("float_rate >", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateGreaterThanOrEqualTo(Long value) {
            addCriterion("float_rate >=", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateLessThan(Long value) {
            addCriterion("float_rate <", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateLessThanOrEqualTo(Long value) {
            addCriterion("float_rate <=", value, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateIn(List<Long> values) {
            addCriterion("float_rate in", values, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateNotIn(List<Long> values) {
            addCriterion("float_rate not in", values, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateBetween(Long value1, Long value2) {
            addCriterion("float_rate between", value1, value2, "floatRate");
            return (Criteria) this;
        }

        public Criteria andFloatRateNotBetween(Long value1, Long value2) {
            addCriterion("float_rate not between", value1, value2, "floatRate");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermIsNull() {
            addCriterion("investment_term is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermIsNotNull() {
            addCriterion("investment_term is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermEqualTo(BigDecimal value) {
            addCriterion("investment_term =", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermNotEqualTo(BigDecimal value) {
            addCriterion("investment_term <>", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermGreaterThan(BigDecimal value) {
            addCriterion("investment_term >", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_term >=", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermLessThan(BigDecimal value) {
            addCriterion("investment_term <", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermLessThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_term <=", value, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermIn(List<BigDecimal> values) {
            addCriterion("investment_term in", values, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermNotIn(List<BigDecimal> values) {
            addCriterion("investment_term not in", values, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_term between", value1, value2, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentTermNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_term not between", value1, value2, "investmentTerm");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyIsNull() {
            addCriterion("investment_min_money is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyIsNotNull() {
            addCriterion("investment_min_money is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyEqualTo(BigDecimal value) {
            addCriterion("investment_min_money =", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyNotEqualTo(BigDecimal value) {
            addCriterion("investment_min_money <>", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyGreaterThan(BigDecimal value) {
            addCriterion("investment_min_money >", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_min_money >=", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyLessThan(BigDecimal value) {
            addCriterion("investment_min_money <", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_min_money <=", value, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyIn(List<BigDecimal> values) {
            addCriterion("investment_min_money in", values, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyNotIn(List<BigDecimal> values) {
            addCriterion("investment_min_money not in", values, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_min_money between", value1, value2, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMinMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_min_money not between", value1, value2, "investmentMinMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyIsNull() {
            addCriterion("investment_max_money is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyIsNotNull() {
            addCriterion("investment_max_money is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyEqualTo(BigDecimal value) {
            addCriterion("investment_max_money =", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyNotEqualTo(BigDecimal value) {
            addCriterion("investment_max_money <>", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyGreaterThan(BigDecimal value) {
            addCriterion("investment_max_money >", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_max_money >=", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyLessThan(BigDecimal value) {
            addCriterion("investment_max_money <", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_max_money <=", value, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyIn(List<BigDecimal> values) {
            addCriterion("investment_max_money in", values, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyNotIn(List<BigDecimal> values) {
            addCriterion("investment_max_money not in", values, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_max_money between", value1, value2, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andInvestmentMaxMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_max_money not between", value1, value2, "investmentMaxMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIsNull() {
            addCriterion("total_money is null");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIsNotNull() {
            addCriterion("total_money is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyEqualTo(BigDecimal value) {
            addCriterion("total_money =", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotEqualTo(BigDecimal value) {
            addCriterion("total_money <>", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyGreaterThan(BigDecimal value) {
            addCriterion("total_money >", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_money >=", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyLessThan(BigDecimal value) {
            addCriterion("total_money <", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_money <=", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIn(List<BigDecimal> values) {
            addCriterion("total_money in", values, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotIn(List<BigDecimal> values) {
            addCriterion("total_money not in", values, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_money between", value1, value2, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_money not between", value1, value2, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIsNull() {
            addCriterion("left_money is null");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIsNotNull() {
            addCriterion("left_money is not null");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyEqualTo(BigDecimal value) {
            addCriterion("left_money =", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotEqualTo(BigDecimal value) {
            addCriterion("left_money <>", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyGreaterThan(BigDecimal value) {
            addCriterion("left_money >", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("left_money >=", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyLessThan(BigDecimal value) {
            addCriterion("left_money <", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("left_money <=", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIn(List<BigDecimal> values) {
            addCriterion("left_money in", values, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotIn(List<BigDecimal> values) {
            addCriterion("left_money not in", values, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_money between", value1, value2, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_money not between", value1, value2, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNull() {
            addCriterion("people is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNotNull() {
            addCriterion("people is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleEqualTo(Integer value) {
            addCriterion("people =", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotEqualTo(Integer value) {
            addCriterion("people <>", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThan(Integer value) {
            addCriterion("people >", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThanOrEqualTo(Integer value) {
            addCriterion("people >=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThan(Integer value) {
            addCriterion("people <", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThanOrEqualTo(Integer value) {
            addCriterion("people <=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleIn(List<Integer> values) {
            addCriterion("people in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotIn(List<Integer> values) {
            addCriterion("people not in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleBetween(Integer value1, Integer value2) {
            addCriterion("people between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotBetween(Integer value1, Integer value2) {
            addCriterion("people not between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("img is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("img is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("img =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("img <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("img >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("img >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("img <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("img <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("img like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("img not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("img in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("img not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("img between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("img not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andFootNameIsNull() {
            addCriterion("foot_name is null");
            return (Criteria) this;
        }

        public Criteria andFootNameIsNotNull() {
            addCriterion("foot_name is not null");
            return (Criteria) this;
        }

        public Criteria andFootNameEqualTo(String value) {
            addCriterion("foot_name =", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameNotEqualTo(String value) {
            addCriterion("foot_name <>", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameGreaterThan(String value) {
            addCriterion("foot_name >", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameGreaterThanOrEqualTo(String value) {
            addCriterion("foot_name >=", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameLessThan(String value) {
            addCriterion("foot_name <", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameLessThanOrEqualTo(String value) {
            addCriterion("foot_name <=", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameLike(String value) {
            addCriterion("foot_name like", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameNotLike(String value) {
            addCriterion("foot_name not like", value, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameIn(List<String> values) {
            addCriterion("foot_name in", values, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameNotIn(List<String> values) {
            addCriterion("foot_name not in", values, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameBetween(String value1, String value2) {
            addCriterion("foot_name between", value1, value2, "footName");
            return (Criteria) this;
        }

        public Criteria andFootNameNotBetween(String value1, String value2) {
            addCriterion("foot_name not between", value1, value2, "footName");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(Short value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(Short value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(Short value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(Short value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(Short value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(Short value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<Short> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<Short> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(Short value1, Short value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(Short value1, Short value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNull() {
            addCriterion("open_time is null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNotNull() {
            addCriterion("open_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeEqualTo(Integer value) {
            addCriterion("open_time =", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotEqualTo(Integer value) {
            addCriterion("open_time <>", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThan(Integer value) {
            addCriterion("open_time >", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_time >=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThan(Integer value) {
            addCriterion("open_time <", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThanOrEqualTo(Integer value) {
            addCriterion("open_time <=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIn(List<Integer> values) {
            addCriterion("open_time in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotIn(List<Integer> values) {
            addCriterion("open_time not in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeBetween(Integer value1, Integer value2) {
            addCriterion("open_time between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("open_time not between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeIsNull() {
            addCriterion("vip_open_time is null");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeIsNotNull() {
            addCriterion("vip_open_time is not null");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeEqualTo(Integer value) {
            addCriterion("vip_open_time =", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeNotEqualTo(Integer value) {
            addCriterion("vip_open_time <>", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeGreaterThan(Integer value) {
            addCriterion("vip_open_time >", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip_open_time >=", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeLessThan(Integer value) {
            addCriterion("vip_open_time <", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeLessThanOrEqualTo(Integer value) {
            addCriterion("vip_open_time <=", value, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeIn(List<Integer> values) {
            addCriterion("vip_open_time in", values, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeNotIn(List<Integer> values) {
            addCriterion("vip_open_time not in", values, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeBetween(Integer value1, Integer value2) {
            addCriterion("vip_open_time between", value1, value2, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andVipOpenTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("vip_open_time not between", value1, value2, "vipOpenTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeIsNull() {
            addCriterion("rate_time is null");
            return (Criteria) this;
        }

        public Criteria andRateTimeIsNotNull() {
            addCriterion("rate_time is not null");
            return (Criteria) this;
        }

        public Criteria andRateTimeEqualTo(Integer value) {
            addCriterion("rate_time =", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotEqualTo(Integer value) {
            addCriterion("rate_time <>", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeGreaterThan(Integer value) {
            addCriterion("rate_time >", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rate_time >=", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeLessThan(Integer value) {
            addCriterion("rate_time <", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("rate_time <=", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeIn(List<Integer> values) {
            addCriterion("rate_time in", values, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotIn(List<Integer> values) {
            addCriterion("rate_time not in", values, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeBetween(Integer value1, Integer value2) {
            addCriterion("rate_time between", value1, value2, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("rate_time not between", value1, value2, "rateTime");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNull() {
            addCriterion("open_status is null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIsNotNull() {
            addCriterion("open_status is not null");
            return (Criteria) this;
        }

        public Criteria andOpenStatusEqualTo(Byte value) {
            addCriterion("open_status =", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotEqualTo(Byte value) {
            addCriterion("open_status <>", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThan(Byte value) {
            addCriterion("open_status >", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("open_status >=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThan(Byte value) {
            addCriterion("open_status <", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusLessThanOrEqualTo(Byte value) {
            addCriterion("open_status <=", value, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusIn(List<Byte> values) {
            addCriterion("open_status in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotIn(List<Byte> values) {
            addCriterion("open_status not in", values, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusBetween(Byte value1, Byte value2) {
            addCriterion("open_status between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andOpenStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("open_status not between", value1, value2, "openStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_basic
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_basic
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}